# Generated by Django 4.2 on 2023-04-16 07:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import app.models.experience


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Telegram"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Эл.почта")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Facebook"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Linkedin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, null=True, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, null=True, verbose_name="Фамилия"),
                ),
                (
                    "job_category",
                    models.TextField(
                        choices=[
                            ("other", "Другое"),
                            ("finance", "Финансы"),
                            ("jurisprudence", "Юриспруденция"),
                            ("IT", "IT"),
                            ("domestic services", "Бытовые услуги"),
                            ("management", "Менеджмент"),
                            ("marketing", "Маркетинг"),
                            ("art", "Искусство"),
                            ("tourism", "Туризм"),
                        ],
                        default="other",
                        max_length=100,
                        verbose_name="Уровень образования",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Должность"
                    ),
                ),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                (
                    "education_level",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("secondary", "Среднее"),
                            ("secondary specialized", "Среднее специальное"),
                            ("incomplete higher", "Неоконченное высшее"),
                            ("higher", "Высшее"),
                            ("bachelor", "Бакалавр"),
                            ("master", "Магистр"),
                            ("PhD", "Кандидат наук"),
                            ("Ph.D", "Доктор наук"),
                        ],
                        default="secondary",
                        max_length=100,
                        verbose_name="Уровень образования",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_contacts",
                        to="app.contacts",
                        verbose_name="Контакты",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=150, verbose_name="Образовательное учреждение"
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Курс/Факультет"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(verbose_name="Специализация/Профессия"),
                ),
                (
                    "started_at",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1970),
                            app.models.experience.max_value_current_year,
                        ],
                        verbose_name="C",
                    ),
                ),
                (
                    "finished_at",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1970),
                            app.models.experience.max_value_current_year,
                        ],
                        verbose_name="По",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=130, null=True, verbose_name="Название компании"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "duties",
                    models.TextField(
                        blank=True, verbose_name="Должностные обязанности"
                    ),
                ),
                (
                    "started_at",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1970),
                            app.models.experience.max_value_current_year,
                        ],
                        verbose_name="C",
                    ),
                ),
                (
                    "finished_at",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1970),
                            app.models.experience.max_value_current_year,
                        ],
                        verbose_name="По",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Vacancy",
        ),
        migrations.AddField(
            model_name="cv",
            name="education",
            field=models.ManyToManyField(
                blank=True,
                related_name="cv_education",
                to="app.education",
                verbose_name="Образование",
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="experience",
            field=models.ManyToManyField(
                blank=True,
                related_name="cv_experience",
                to="app.education",
                verbose_name="Образование",
            ),
        ),
    ]
