# Generated by Django 4.2 on 2023-04-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_contacts_cv_education_experience_delete_vacancy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="salary",
            field=models.IntegerField(null=True, verbose_name="Зарплата"),
        ),
    ]
