# Generated by Django 4.2 on 2023-04-18 23:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_cv_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="education",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="experience",
        ),
    ]
