# Generated by Django 4.2 on 2023-04-18 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_remove_cv_education_remove_cv_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education",
                to="app.cv",
                verbose_name="Контакты",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to="app.cv",
                verbose_name="опыт",
            ),
        ),
    ]
