# Generated by Django 4.2 on 2023-04-19 01:35

import django.core.validators
import month.models
from django.db import migrations, models

import app.models.experience


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_education_cv_experience_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="month",
            field=month.models.MonthField(
                blank=True,
                help_text="some help...",
                null=True,
                verbose_name="Month Value",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="course",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Курс/Факультет"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="finished_at",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1960),
                    app.models.experience.max_value_current_year,
                ],
                verbose_name="По",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="place",
            field=models.CharField(
                max_length=500, verbose_name="Образовательное учреждение"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="started_at",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1960),
                    app.models.experience.max_value_current_year,
                ],
                verbose_name="C",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="finished_at",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1960),
                    app.models.experience.max_value_current_year,
                ],
                verbose_name="По",
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="started_at",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1960),
                    app.models.experience.max_value_current_year,
                ],
                verbose_name="C",
            ),
        ),
    ]
