# Generated by Django 4.2 on 2023-04-19 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_education_month_alter_education_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="education",
            name="month",
        ),
    ]
