# Generated by Django 4.2 on 2023-04-20 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0008_alter_contacts_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=50, verbose_name="Должность"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("other", "Другое"),
                            ("finance", "Финансы"),
                            ("jurisprudence", "Юриспруденция"),
                            ("IT", "IT"),
                            ("domestic services", "Бытовые услуги"),
                            ("management", "Менеджмент"),
                            ("marketing", "Маркетинг"),
                            ("art", "Искусство"),
                            ("tourism", "Туризм"),
                        ],
                        default="other",
                        verbose_name="Категория",
                    ),
                ),
                ("salary", models.IntegerField(verbose_name="Зарплата")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание вакансии"
                    ),
                ),
                (
                    "min_experience",
                    models.IntegerField(verbose_name="Минимальный опыт"),
                ),
                (
                    "max_experience",
                    models.IntegerField(verbose_name="Максимальный опыт"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, verbose_name="Видимость вакансии"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
