# Generated by Django 4.2 on 2023-04-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_cv_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
