# Generated by Django 4.2 on 2023-04-20 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_cv_status"),
        ("app", "0009_vacancy"),
    ]

    operations = []
