# Generated by Django 4.2 on 2023-04-20 02:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_cv_published"),
        ("app", "0010_merge_0009_cv_status_0009_vacancy"),
    ]

    operations = []
